spring:
  application:
    name: test-hub
  datasource:
    url: jdbc:postgresql://localhost:5432/test-hub
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855